### ISSUE TITLE
Set a default for displaying the configuration in the CMS

### ISSUE THREAD

**Issue by edwilde** [silverstripe/silverstripe-sitebanner#21]
In `v3.0.0` _(I think)_ the `SITEBANNER_SITECONFIG` and `SITEBANNER_MODELADMIN` variables were introduced to configure how the administration should be displayed in the CMS.

If neither of these are set, then the administration is **not shown anywhere in the CMS**. This makes the upgrade path much more challenging, as the administration will just _disappear_ for the module, leading people to assume it is broken or missing.

I would suggest a couple of things:
* Set the administration for this module to be in its own model admin by default, while still allowing people switch it to site config if they want.
* Add documentation/functionality to set this configuration without an environment variable, e.g. via a `yml` config

**Comment by satrun77** [comment]
> In v3.0.0 (I think) the SITEBANNER_SITECONFIG and SITEBANNER_MODELADMIN variables were introduced to configure how the administration should be displayed in the CMS.

Yes

> Set the administration for this module to be in its own model admin by default, while still allowing people switch it to site config if they want

This sound good. Are you planning to submit a pull request? :) if busy, I will do it this week

**Comment by edwilde** [comment]
> Are you planning to submit a pull request?

Maybe, although I certainly doubt I would get chance this week
