### ISSUE TITLE
SITEBANNER_SITECONFIG=1 disable CMS sitebanner section from CMS

### ISSUE THREAD

**Issue by pack254** [silverstripe/silverstripe-sitebanner#30]
When I add `SITEBANNER_SITECONFIG=1` to `.env` file it disabled the Site Banner section from the CMS. I am not sure  this is a usual behavior of it, but I would assume the module should be activated when we set `SITEBANNER_SITECONFIG=1`. 

The version I have found this problem is `3.0.1`

**Comment by satrun77** [comment]
`SITEBANNER_SITECONFIG` is not to activate or deactivate the module. 

The module creates a grid field in the CMS settings section in an older version. Notes in readme file https://github.com/silverstripe/silverstripe-sitebanner?tab=readme-ov-file#site-settings

You should only use this if you have this module installed and you still want the old way, which is not recommended. You should leave it as the default https://github.com/silverstripe/silverstripe-sitebanner?tab=readme-ov-file#model-admin

**Comment by pack254** [comment]
Thank for your answer Mo this is make me clear now. Cheers 🥳
