### ISSUE TITLE
Tag a stable release

### ISSUE THREAD

**Issue by elliot-sawyer** [silverstripe/silverstripe-sitebanner#9]

**Comment by NightJar** [comment]
Which version would you like tagged @elliot-sawyer ?
SS4 or SS3?

**Comment by elliot-sawyer** [comment]
I forgot I raised this! SS4 pls

**Comment by NightJar** [comment]
Actually I notice there are no tags at all 😅 
I'll add one from the 1.0 branch, and one from master for SS4 :)

I'll leave this open until such time as the releases are made
(Just sorting out the open PRs at the moment).

**Comment by NightJar** [comment]
An update:
Just going to do some actual usage testing before marking stable versions :)
I intend to tag `1.0` branch current HEAD as 1.0.0, and `master` current HEAD as 2.0.0 - unless issues are found.
